spring.application.name=ss6_project_quiz

# Database - Gi? nguyên logic c?a b?n
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ss6_project_quiz2?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:ad1412}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
server.port=${PORT:8080}
spring.messages.encoding=UTF-8

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

groq.api.key=${GROQ_API_KEY}

spring.jackson.mapper.default-view-inclusion=true